### ISSUE TITLE
FF: revealed content displays under previous steps

### ISSUE THREAD

**Issue by bennypowers** [ruphin/slidem#4]
Consider this slide:

```html
<style>
  zero-md {
    display: block;
  }

  [floating] {
    position: absolute;
    right: 0;
    left: 0;
  }

  [explanation] {
    margin: 2em;
  }
</style>

<slidem-slide id="maybe-monad-applicative" background="--primary">
  <h2>Maybe Monad - Binary</h2>
  <div explanation floating>
    <p>Wait!! People code like that?</p>
    <br/>
    <br/>
    <p reveal><strong><em>👉 NOPE 👈</em></strong></span></p>
    <br/>
    <br/>
    <p reveal>Monads are also applicatives, which means we can lift any function into 'monadic space' with <code>lift</code></p>
  </div>
  <zero-md reveal src="markdown/monads-maybe-applicative.md"></zero-md>
</slidem-slide>
```

And how it renders (at https://bennypowers.dev/starting-functional-javascript/#slide-22/step-4) on macOS 10.14 in Firefox 66, Safari 12.1, and Chrome 73

Firefox:

<img width="2672" alt="Screenshot 2019-04-06 22 20 42" src="https://user-images.githubusercontent.com/1466420/55674223-410c5780-58ba-11e9-8c15-89d8e50eed77.png">

Safari:
<img width="2560" alt="Screenshot 2019-04-06 22 23 04" src="https://user-images.githubusercontent.com/1466420/55674246-9c3e4a00-58ba-11e9-8064-ad79726d0631.png">

Chrome: 
<img width="2672" alt="Screenshot 2019-04-06 22 20 19" src="https://user-images.githubusercontent.com/1466420/55674226-45387500-58ba-11e9-964c-542bdcdbf0cf.png">

The slide renders as intended on Chrome, with the initial content hidden beneath the revealed content. In Firefox and Safari, however, the revealed content is below the initial content.

**Comment by ruphin** [comment]
Neat! I love cross-browser compatibility issues. Digging right in :)

**Comment by ruphin** [comment]
Found the problem. The `zero-md` element has a style `contain: content` that is not recognised on non-chrome browsers. This is also why the top and bottom padding disappears in the markdown frame. If this rule is removed, Chrome behaves the same as the other browsers.

It's trivial to fix, the `zero-md` element just needs a classic `overflow: auto` or `overflow: hidden` as a fallback to the newer `content` CSS rule.

Super nice deck! :)

**Comment by bennypowers** [comment]
[Looks like that one it's pretty stagnant](https://developer.mozilla.org/en-US/docs/Web/CSS/contain). Hopefully it will get the `<datalist>` treatment from 🍎 soon.

Thanks for looking in to this. I'll open an issue at zero-md

**Comment by zerodevx** [comment]
@bennypowers  I think this is more of a stacking context issue. Making an element `position:absolute` breaks it out of the current block flow. If you intend to cover that element with another, you'll have to break that one out too. Adding `floating` to the `<zero-md>` tag fixes this.

```html
<style>
  zero-md {
    display: block;
  }

  [floating] {
    position: absolute;
    right: 0;
    left: 0;
  }

  [explanation] {
    margin: 2em;
  }
</style>

<slidem-slide id="maybe-monad-applicative" background="--primary">
  <h2>Maybe Monad - Binary</h2>

  <!-- This block is always gonna appear above because of position:absolute -->
  <div explanation floating> 
    <p>Wait!! People code like that?</p>
    <br/>
    <br/>
    <p reveal><strong><em>👉 NOPE 👈</em></strong></span></p>
    <br/>
    <br/>
    <p reveal>Monads are also applicatives, which means we can lift any function into 'monadic space' with <code>lift</code></p>
  </div>

  <!-- Adding `floating` here makes the element have higher stacking specificity -->
  <zero-md reveal floating src="markdown/monads-maybe-applicative.md"></zero-md>

</slidem-slide>
```

Here's another slide that probably should have `floating` added: https://bennypowers.dev/starting-functional-javascript/#slide-20/step-5

But @ruphin has a point with `contain:content` though - it "masked" the problem in Chrome. That's because a (side) effect of this declaration is it forces a new containing block at a higher stacking order. 

For *most* use-cases, having `contain:content` shouldn't change how the layout is painted when being rendered in the shadow dom - it's intended to hint to (supported) browsers that descendant changes shouldn't require a document-level repaint. It shouldn't change how `overflow` is declared, so for the strange padding issue, I'm not sure if it's related to the `overflow` property (though that fixed it).  

I'm toggling `contain:content` on other websites using this component and I don't see any layout changes, padding or otherwise... Not sure if I wanna go down the rabbit hole on that one. 😆 

Oh and really nice slides btw!
